version: "3"
services:
  front:
    build:
      context: .
    # depends_on:
    #   - api
    # user: root
    # user: afidegnum:afidegnum
    user: "1000:1000"
    volumes:
      - mysocket:/tmp:rw
      - ./static/:/app/static/
    environment:
      - PERSEUS_HOST=0.0.0.0
      - PERSEUS_PORT=4401
      - CUSTOMERS_HOST=api
    ports:
      - 4401:4401
    expose:
      - "4401"
    # healthcheck:
    #   test: curl --fail http://localhost:4401/ || exit 1
    #   interval: 50s
    #   timeout: 20s
    #   retries: 5
networks:
  default:
    name: mynet
    external: true

volumes:
  mysocket:
    external: true
