version: "3"
services:
  db:
    build:
      context: .
    user: root
    volumes:
      - ../Data/pgdata:/var/lib/postgresql/data
      - ../Data/db/:/docker-entrypoint-initdb.d/
    environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=chou1979
      - POSTGRES_USER=isonet
      - POSTGRES_PASSWORD=iso2023
      - POSTGRES_DB=isonet
    ports:
      - "5432:5432"
    expose:
      - "5432"
networks:
  default:
    external:
      name: mynet

