version: "3"
services:
  api:
    build:
      context: .
      args:
        UID: 1000
        GID: 1000
    restart: always
    user: "1000:1000"
    volumes:
      - mysocket:/tmp:rw
    env_file:
      - .env
    ports:
      - 4400:4400
    expose:
      - "4400"
    environment:
      - PG.HOST=db
networks:
  default:
    name: mynet
    external: true
volumes:
  mysocket:
    external: true
